using System;
using System.Linq;
using UnityEngine;

namespace PX
{
    public class CodeGenerator_GameDB_Client : CodeGeneratorBase
    {
        public CodeGenerator_GameDB_Client(string InFileName, string InOutputPathCS, bool isDebug)
        {
            OutputLanguage = CodeGeneratorBase.OutputLanguageType.CSharp;
            generatorCS = new GenerateCodeWriter_GameDB_Client(InFileName, InOutputPathCS, isDebug);
        }

        public override string GenerateTry()
        {
            // CommonCoreData 상속 받은 모든 클래스별로 프로퍼티의 Type 수집.
            GenerateCodeContext context = CreteCodeContext(typeof(IGameDBServer_Disposable));
            Debug.Assert(context.Types.Count > 0);
            Debug.Assert(context.Enums.Count > 0);

            // 문자열로 출력
            generatorCS.WriteToStringBuilder(context);

            generatorCS.WriteTempFile();
            bool IsNew = generatorCS.ReplaceWhenDiff();

            return DisplayResult(IsNew);
        }

        public override void FillMemberInfo(MemberDefinition member, Type type, GenerateCodeContext context)
        {
            // Map
            Type dictionaryType = IsClosedDictionaryType(type) ? type : type.GetInterfaces().FirstOrDefault(IsClosedDictionaryType);
            if (dictionaryType != null)
            {
                member.IsMapOrArray = true;
                string keyType = GetTypeRef(dictionaryType.GetGenericArguments().ElementAt(0), context);
                string valueType = GetTypeRef(dictionaryType.GetGenericArguments().ElementAt(1), context);

                DictionaryEnumKey dictionaryEnumKey = member.GetCustomAttribute<DictionaryEnumKey>();
                if (dictionaryEnumKey != null && keyType == "string")
                {
                    // ex) GameDBEquipment.cs
                    // [DictionaryEnumKey(typeof(EEquipmentMythic))]
                    // Map 의 key 값을 커스텀 어트리뷰트의 DictionaryEnumKey 타입으로 바꿔준다.
                    CreateEnumContext(dictionaryEnumKey.keyType, context);
                    keyType = GetTypeRef(dictionaryEnumKey.keyType, context);
                    member.Type = $"Dictionary<{keyType}, {valueType}>";
                }
            }
        }
    }

    public class GenerateCodeWriter_GameDB_Client : GenerateCodeWriter
    {
        public GenerateCodeWriter_GameDB_Client(string InFileName, string InOutputPath, bool isDebug)
        {
            Initialize(InFileName, ".cs", InOutputPath, isDebug);
        }

        private string ConvertToCryptoValueType(string type)
        {
            switch (type)
            {
                case "bool":
                    return "CryptoValueBool";
                case "int":
                    return "CryptoValueInt";
                case "double":
                case "float":
                    return "CryptoValueDouble";
                default:
                    return type;
            }
        }

        public override bool WriteToStringBuilder(GenerateCodeContext context)
        {
            GenerateAutoGeneratedComment("CodeGenerator_GameDBData_Client.cs");

            // import
            sb.AppendLine($"using System;");
            sb.AppendLine($"using System.Collections.Generic;");
            sb.AppendLine($"using UnityEngine;");
            sb.AppendLine($"using Firebase.Firestore;");
            sb.AppendLine();

            // namespace {
            sb.AppendLine($"namespace PX");
            sb.AppendLine($"{{");

            // "Server" to "Client"
            foreach (TypeDefinition t in context.Types)
            {
                t.ReplaceString("Server", "Client");
            }

            // class
            foreach (TypeDefinition t in context.Types)
            {
                // if (t.Name == "GameDB_ClientMailboxItem")
                // {
                //     Debug.Log($"typeDef : {t.Name}");
                // }

                if (HasExcludeAttribute(t.ClrType)) // [ExcludeCodeGenerate]
                    continue;

                if (t.ClrType.IsInterface || t.ClrType.IsAbstract)
                    continue;

                sb.AppendLine($"{INTEND1}{t.Declaration}"); // class start
                sb.AppendLine($"{INTEND1}{{");

                // Dispose()
                if (t.ClrType.BaseType == typeof(IGameDBServer_Disposable))
                {
                    sb.AppendLine($"{INTEND2}public override void Dispose()");
                    sb.AppendLine($"{INTEND2}{{");
                    sb.AppendLine($"{INTEND3}Dispose(disposing: true);");
                    sb.AppendLine($"{INTEND3}GC.SuppressFinalize(this);");
                    sb.AppendLine($"{INTEND2}}}");
                    sb.AppendLine();

                    sb.AppendLine($"{INTEND2}private bool disposedValue;");
                    sb.AppendLine($"{INTEND2}private void Dispose(bool disposing)");
                    sb.AppendLine($"{INTEND2}{{");
                    sb.AppendLine($"{INTEND3}if (!disposedValue)");
                    sb.AppendLine($"{INTEND3}{{");
                    sb.AppendLine($"{INTEND4}disposedValue = true;");
                    sb.AppendLine($"{INTEND4}if (disposing)");
                    sb.AppendLine($"{INTEND4}{{");
                    foreach (MemberDefinition m in t.Members)
                    {
                        sb.AppendLine($"{INTEND5}{m.Name} = null;");
                    }
                    sb.AppendLine($"{INTEND4}}}");
                    sb.AppendLine($"{INTEND3}}}");
                    sb.AppendLine($"{INTEND2}}}");
                    sb.AppendLine();

                    sb.AppendLine($"{INTEND2}public void Initialize()");
                    sb.AppendLine($"{INTEND2}{{");
                    foreach (MemberDefinition m in t.Members)
                    {
                        sb.AppendLine($"{INTEND3}{m.Name} = new {m.Type}();");
                    }
                    foreach (MemberDefinition m in t.Members)
                    {
                        sb.AppendLine($"{INTEND3}DBDataKeyList.Add(\"{m.Name}\");");
                    }
                    sb.AppendLine($"{INTEND2}}}");
                    sb.AppendLine();
                }
                // members
                {
                    foreach (MemberDefinition m in t.Members)
                    {
                        string cryptoValueType = ConvertToCryptoValueType(m.Type);
                        sb.AppendLine($"{INTEND2}public {cryptoValueType} {m.Name} {{ get; set; }}");
                    }
                }

                sb.AppendLine($"{INTEND1}}}"); // class end
                sb.AppendLine();
            }

            // namespace }
            sb.AppendLine($"}}");

            sb.Replace("\r\n", "\n").Replace("\r", "\n").Replace("\n", "\r\n");

            return true;
        }
    }
}
