using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PX
{
    /// <summary>
    /// TypeScript 마이그레이션 코드 생성 템플릿
    /// </summary>
    public static class CoreDataMigrationTemplates
    {
        private const string INDENT1 = "    ";
        private const string INDENT2 = "        ";

        /// <summary>
        /// 파일 헤더 생성 (공통 타입 import 포함)
        /// </summary>
        public static string GenerateFileHeader(string coreDataName, HashSet<string> usedTypes = null)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated; DO NOT EDIT!");
            sb.AppendLine("// source: CodeGenerator_CoreDataMigration.cs");
            sb.AppendLine($"// CoreData: {coreDataName}");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();

            // MigrationFunction import
            sb.AppendLine("import { MigrationFunction } from \"../CoreDataMigration\";");

            // 공통 타입 import (Generated 폴더에서 3단계 위로)
            sb.AppendLine("import { ModValue, ModValueInt, ModValueDouble, ModValueBool } from \"../../../Data/Shared/Types/ModValueTypes\";");
            sb.AppendLine("import { PXBigInt } from \"../../../Data/Shared/Types/BigIntTypes\";");

            // 사용된 Enum들 import (CommonEnum에서)
            if (usedTypes != null && usedTypes.Count > 0)
            {
                var enumTypes = usedTypes.Where(t => t.StartsWith("E") && char.IsUpper(t[1])).ToList();
                if (enumTypes.Count > 0)
                {
                    string enumImports = string.Join(", ", enumTypes.OrderBy(e => e));
                    sb.AppendLine($"import {{ {enumImports} }} from \"../../../Data/Generated/CommonEnum\";");
                }

                // CoreData 타입들 import (CoreData_ 접두사 또는 Info 접미사)
                var coreDataTypes = usedTypes.Where(t =>
                    t.StartsWith("CoreData_") ||
                    t.EndsWith("Info") ||
                    t.EndsWith("Data")).ToList();
                if (coreDataTypes.Count > 0)
                {
                    string coreDataImports = string.Join(", ", coreDataTypes.OrderBy(c => c));
                    sb.AppendLine($"import {{ {coreDataImports} }} from \"../../../Data/Generated/CoreData\";");
                }
            }

            sb.AppendLine();

            return sb.ToString();
        }

        /// <summary>
        /// 스키마에서 사용된 타입들 수집
        /// </summary>
        public static HashSet<string> CollectUsedTypes(List<SchemaVersion> versions)
        {
            var usedTypes = new HashSet<string>();

            foreach (var version in versions)
            {
                if (version.Schema?.Fields == null) continue;

                foreach (var field in version.Schema.Fields.Values)
                {
                    ExtractTypesFromTypeString(field.TypeScriptType, usedTypes);
                }
            }

            return usedTypes;
        }

        /// <summary>
        /// 타입 문자열에서 실제 타입들 추출
        /// </summary>
        private static void ExtractTypesFromTypeString(string typeStr, HashSet<string> usedTypes)
        {
            if (string.IsNullOrEmpty(typeStr)) return;

            // Map<K, V> 또는 Array<T> 형태 처리
            if (typeStr.StartsWith("Map<") || typeStr.StartsWith("Array<"))
            {
                // 제네릭 파라미터 추출
                int start = typeStr.IndexOf('<') + 1;
                int end = typeStr.LastIndexOf('>');
                if (start > 0 && end > start)
                {
                    string inner = typeStr.Substring(start, end - start);
                    // 쉼표로 분리 (Map의 경우)
                    foreach (string part in inner.Split(','))
                    {
                        ExtractTypesFromTypeString(part.Trim(), usedTypes);
                    }
                }
            }
            else
            {
                // 기본 타입 제외
                if (typeStr == "string" || typeStr == "number" || typeStr == "boolean" || typeStr == "any")
                    return;

                // ModValue 계열은 이미 공통 import에 포함
                if (typeStr.StartsWith("ModValue") || typeStr == "PXBigInt")
                    return;

                usedTypes.Add(typeStr);
            }
        }

        /// <summary>
        /// 인터페이스 정의 생성
        /// </summary>
        public static string GenerateInterface(string coreDataName, string version, CoreDataSchema schema, bool isLatest)
        {
            var sb = new StringBuilder();
            string versionSuffix = version.Replace(".", "_");
            string interfaceName = isLatest
                ? $"{coreDataName}_Data_Latest"
                : $"{coreDataName}_Data_v{versionSuffix}";

            sb.AppendLine($"interface {interfaceName} {{");

            foreach (var field in schema.Fields.Values)
            {
                sb.AppendLine($"{INDENT1}{field.Name}?: {field.TypeScriptType};");
            }

            sb.AppendLine($"{INDENT1}[str: string]: any;");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 버전별 인터페이스 상속 체인 생성
        /// </summary>
        public static string GenerateInterfaceChain(string coreDataName, List<SchemaVersion> versions)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine($"// {coreDataName} - Auto-generated interfaces");
            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine();

            for (int i = 0; i < versions.Count; i++)
            {
                var version = versions[i];
                bool isLatest = i == versions.Count - 1;
                string versionSuffix = version.Version.Replace(".", "_");

                if (i == 0)
                {
                    // 첫 버전: 기본 인터페이스
                    sb.AppendLine($"interface {coreDataName}_Data_v{versionSuffix} {{");
                    foreach (var field in version.Schema.Fields.Values)
                    {
                        sb.AppendLine($"{INDENT1}{field.Name}?: {field.TypeScriptType};");
                    }
                    sb.AppendLine($"{INDENT1}[str: string]: any;");
                    sb.AppendLine("}");
                }
                else
                {
                    // 이후 버전: 이전 버전 상속
                    string prevVersionSuffix = versions[i - 1].Version.Replace(".", "_");
                    sb.AppendLine();
                    sb.AppendLine($"interface {coreDataName}_Data_v{versionSuffix} extends {coreDataName}_Data_v{prevVersionSuffix} {{");

                    // 변경된 필드만 추가
                    if (version.Changes != null)
                    {
                        foreach (var change in version.Changes)
                        {
                            if (change.Type == SchemaChangeType.FieldAdded)
                            {
                                sb.AppendLine($"{INDENT1}{change.FieldName}?: {change.NewType};");
                            }
                            else if (change.Type == SchemaChangeType.FieldRenamed)
                            {
                                sb.AppendLine($"{INDENT1}{change.FieldName}?: {change.NewType};");
                            }
                        }
                    }
                    sb.AppendLine("}");
                }

                // Latest 인터페이스
                if (isLatest)
                {
                    sb.AppendLine();
                    sb.AppendLine($"interface {coreDataName}_Data_Latest extends {coreDataName}_Data_v{versionSuffix} {{}}");
                }
            }

            return sb.ToString();
        }

        /// <summary>
        /// 필드 추가 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateFieldAddedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}return {{ ...data, {change.FieldName}: {change.DefaultValue} }};
{INDENT1}}},";
        }

        /// <summary>
        /// 필드 삭제 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateFieldRemovedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}const {{ {change.FieldName}, ...rest }} = data;
{INDENT2}return rest;
{INDENT1}}},";
        }

        /// <summary>
        /// 필드 이름 변경 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateFieldRenamedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}const {{ {change.OldFieldName}, ...rest }} = data;
{INDENT2}return {{ ...rest, {change.FieldName}: {change.OldFieldName} }};
{INDENT1}}},";
        }

        /// <summary>
        /// 필드 타입 변경 마이그레이션 함수 생성 (TODO 포함)
        /// </summary>
        public static string GenerateFieldTypeChangedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}// [AUTO-GENERATED] TODO: {change.FieldName} 타입 변환 필요
{INDENT2}// 이전 타입: {change.OldType}
{INDENT2}// 새 타입: {change.NewType}
{INDENT2}const {{ {change.FieldName}, ...rest }} = data;
{INDENT2}return {{ ...rest, {change.FieldName}: {change.FieldName} /* TODO: 변환 로직 구현 */ }};
{INDENT1}}},";
        }

        // -----------------------------------------------
        // 중첩 필드 마이그레이션 템플릿
        // -----------------------------------------------

        /// <summary>
        /// 중첩 필드 추가 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateNestedFieldAddedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            // LoginInfo.NewField -> ["LoginInfo", "NewField"]
            string[] pathParts = change.NestedFieldPath.Split('.');
            string parentField = pathParts[0];
            string fieldName = pathParts[pathParts.Length - 1];

            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}// 중첩 필드 추가: {change.NestedFieldPath}
{INDENT2}return {{
{INDENT2}    ...data,
{INDENT2}    {parentField}: {{
{INDENT2}        ...data.{parentField},
{INDENT2}        {fieldName}: {change.DefaultValue}
{INDENT2}    }}
{INDENT2}}};
{INDENT1}}},";
        }

        /// <summary>
        /// 중첩 필드 삭제 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateNestedFieldRemovedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            string[] pathParts = change.NestedFieldPath.Split('.');
            string parentField = pathParts[0];
            string fieldName = pathParts[pathParts.Length - 1];

            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}// 중첩 필드 삭제: {change.NestedFieldPath}
{INDENT2}const {{ {fieldName}, ...rest{parentField} }} = data.{parentField};
{INDENT2}return {{
{INDENT2}    ...data,
{INDENT2}    {parentField}: rest{parentField}
{INDENT2}}};
{INDENT1}}},";
        }

        /// <summary>
        /// 중첩 필드 이름 변경 마이그레이션 함수 생성
        /// </summary>
        public static string GenerateNestedFieldRenamedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            string[] pathParts = change.NestedFieldPath.Split('.');
            string parentField = pathParts[0];
            string oldFieldName = change.OldFieldName ?? change.FieldName;
            string newFieldName = change.FieldName;

            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}// 중첩 필드 이름 변경: {change.NestedFieldPath}
{INDENT2}const {{ {oldFieldName}, ...rest{parentField} }} = data.{parentField};
{INDENT2}return {{
{INDENT2}    ...data,
{INDENT2}    {parentField}: {{
{INDENT2}        ...rest{parentField},
{INDENT2}        {newFieldName}: {oldFieldName}
{INDENT2}    }}
{INDENT2}}};
{INDENT1}}},";
        }

        /// <summary>
        /// 중첩 필드 타입 변경 마이그레이션 함수 생성 (TODO 포함)
        /// </summary>
        public static string GenerateNestedFieldTypeChangedMigration(string version, string prevInterface, string newInterface, SchemaChange change)
        {
            string[] pathParts = change.NestedFieldPath.Split('.');
            string parentField = pathParts[0];
            string fieldName = pathParts[pathParts.Length - 1];

            return $@"{INDENT1}""{version}"": (data: {prevInterface}): {newInterface} => {{
{INDENT2}// [AUTO-GENERATED] TODO: 중첩 필드 {change.NestedFieldPath} 타입 변환 필요
{INDENT2}// 이전 타입: {change.OldType}
{INDENT2}// 새 타입: {change.NewType}
{INDENT2}const {{ {fieldName}, ...rest{parentField} }} = data.{parentField};
{INDENT2}return {{
{INDENT2}    ...data,
{INDENT2}    {parentField}: {{
{INDENT2}        ...rest{parentField},
{INDENT2}        {fieldName}: {fieldName} /* TODO: 변환 로직 구현 */
{INDENT2}    }}
{INDENT2}}};
{INDENT1}}},";
        }

        /// <summary>
        /// 마이그레이션 함수 객체 생성
        /// </summary>
        public static string GenerateMigrationObject(string coreDataName, List<SchemaVersion> versions)
        {
            var sb = new StringBuilder();

            sb.AppendLine();
            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine($"// {coreDataName} - Auto-generated migrations");
            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine($"export const {coreDataName}_Migrations_Generated: {{ [key: string]: MigrationFunction<any, any> }} = {{");

            for (int i = 1; i < versions.Count; i++)
            {
                var version = versions[i];
                var prevVersion = versions[i - 1];

                if (version.Changes == null || version.Changes.Count == 0)
                    continue;

                string prevVersionSuffix = prevVersion.Version.Replace(".", "_");
                string newVersionSuffix = version.Version.Replace(".", "_");
                string prevInterface = $"{coreDataName}_Data_v{prevVersionSuffix}";
                string newInterface = $"{coreDataName}_Data_v{newVersionSuffix}";

                // 같은 버전의 모든 변경사항을 하나의 함수로 병합
                string migrationCode = GenerateMergedMigration(version.Version, prevInterface, newInterface, version.Changes);
                if (!string.IsNullOrEmpty(migrationCode))
                {
                    sb.AppendLine(migrationCode);
                }
            }

            sb.AppendLine("};");

            return sb.ToString();
        }

        /// <summary>
        /// 같은 버전의 여러 변경사항을 하나의 마이그레이션 함수로 병합
        /// </summary>
        private static string GenerateMergedMigration(string version, string prevInterface, string newInterface, List<SchemaChange> changes)
        {
            if (changes == null || changes.Count == 0)
                return string.Empty;

            // 변경 타입별로 분류
            var addedFields = changes.Where(c => c.Type == SchemaChangeType.FieldAdded).ToList();
            var removedFields = changes.Where(c => c.Type == SchemaChangeType.FieldRemoved).ToList();
            var renamedFields = changes.Where(c => c.Type == SchemaChangeType.FieldRenamed).ToList();
            var typeChangedFields = changes.Where(c => c.Type == SchemaChangeType.FieldTypeChanged).ToList();
            var nestedAddedFields = changes.Where(c => c.Type == SchemaChangeType.NestedFieldAdded).ToList();
            var nestedRemovedFields = changes.Where(c => c.Type == SchemaChangeType.NestedFieldRemoved).ToList();
            var nestedRenamedFields = changes.Where(c => c.Type == SchemaChangeType.NestedFieldRenamed).ToList();
            var nestedTypeChangedFields = changes.Where(c => c.Type == SchemaChangeType.NestedFieldTypeChanged).ToList();

            var sb = new StringBuilder();
            sb.AppendLine($"{INDENT1}\"{version}\": (data: {prevInterface}): {newInterface} => {{");

            // 삭제할 필드 처리 (먼저 추출)
            if (removedFields.Count > 0)
            {
                string removedFieldNames = string.Join(", ", removedFields.Select(c => c.FieldName));
                sb.AppendLine($"{INDENT2}const {{ {removedFieldNames}, ...rest }} = data;");
            }

            // 이름 변경 필드 처리
            foreach (var change in renamedFields)
            {
                sb.AppendLine($"{INDENT2}const {change.FieldName} = data.{change.OldFieldName};");
            }

            // 타입 변경 필드 처리
            foreach (var change in typeChangedFields)
            {
                string convertCode = GenerateTypeConversionCode(change.FieldName, change.OldType, change.NewType);
                sb.AppendLine($"{INDENT2}{convertCode}");
            }

            // 중첩 필드 삭제를 위한 부모 필드 처리
            var nestedRemovedByParent = nestedRemovedFields.GroupBy(c => c.NestedFieldPath.Split('.')[0]).ToList();
            foreach (var group in nestedRemovedByParent)
            {
                string parentField = group.Key;
                var fieldNames = group.Select(c => c.NestedFieldPath.Split('.').Last()).ToList();
                string removedNames = string.Join(", ", fieldNames);
                sb.AppendLine($"{INDENT2}const {{ {removedNames}, ...rest_{parentField} }} = data.{parentField} || {{}};");
            }

            // 중첩 필드 이름 변경 처리
            var nestedRenamedByParent = nestedRenamedFields.GroupBy(c => c.NestedFieldPath.Split('.')[0]).ToList();
            foreach (var group in nestedRenamedByParent)
            {
                string parentField = group.Key;
                foreach (var change in group)
                {
                    string oldFieldName = change.OldFieldName ?? change.FieldName;
                    string newFieldName = change.FieldName;
                    sb.AppendLine($"{INDENT2}const renamed_{parentField}_{newFieldName} = data.{parentField}?.{oldFieldName};");
                }
            }

            // 중첩 필드 타입 변경 처리
            foreach (var change in nestedTypeChangedFields)
            {
                string parentField = change.NestedFieldPath.Split('.')[0];
                string fieldName = change.NestedFieldPath.Split('.').Last();
                string convertCode = GenerateTypeConversionCode($"data.{parentField}?.{fieldName}", change.OldType, change.NewType);
                sb.AppendLine($"{INDENT2}const converted_{parentField}_{fieldName} = {convertCode.Replace($"const converted_{parentField}_{fieldName} = ", "")};");
            }

            // return 문 생성
            sb.Append($"{INDENT2}return {{ ");

            // 기존 데이터 스프레드
            if (removedFields.Count > 0)
                sb.Append("...rest");
            else
                sb.Append("...data");

            // 추가 필드
            foreach (var change in addedFields)
            {
                sb.Append($", {change.FieldName}: {change.DefaultValue}");
            }

            // 이름 변경 필드 (새 이름으로)
            foreach (var change in renamedFields)
            {
                sb.Append($", {change.FieldName}: {change.FieldName}");
            }

            // 타입 변경 필드
            foreach (var change in typeChangedFields)
            {
                sb.Append($", {change.FieldName}: converted_{change.FieldName}");
            }

            // 중첩 필드 처리 (추가, 삭제, 이름변경, 타입변경 통합)
            var allNestedChanges = nestedAddedFields
                .Concat(nestedRemovedFields)
                .Concat(nestedRenamedFields)
                .Concat(nestedTypeChangedFields)
                .GroupBy(c => c.NestedFieldPath.Split('.')[0])
                .ToList();

            foreach (var group in allNestedChanges)
            {
                string parentField = group.Key;
                bool hasRemoved = nestedRemovedByParent.Any(g => g.Key == parentField);

                sb.Append($", {parentField}: {{ ");
                if (hasRemoved)
                    sb.Append($"...rest_{parentField}");
                else
                    sb.Append($"...data.{parentField}");

                // 추가된 중첩 필드
                foreach (var change in group.Where(c => c.Type == SchemaChangeType.NestedFieldAdded))
                {
                    string fieldName = change.NestedFieldPath.Split('.').Last();
                    sb.Append($", {fieldName}: {change.DefaultValue}");
                }

                // 이름 변경된 중첩 필드
                foreach (var change in group.Where(c => c.Type == SchemaChangeType.NestedFieldRenamed))
                {
                    string newFieldName = change.FieldName;
                    sb.Append($", {newFieldName}: renamed_{parentField}_{newFieldName}");
                }

                // 타입 변경된 중첩 필드
                foreach (var change in group.Where(c => c.Type == SchemaChangeType.NestedFieldTypeChanged))
                {
                    string fieldName = change.NestedFieldPath.Split('.').Last();
                    sb.Append($", {fieldName}: converted_{parentField}_{fieldName}");
                }

                sb.Append(" }");
            }

            sb.AppendLine(" };");
            sb.Append($"{INDENT1}}},");

            return sb.ToString();
        }

        /// <summary>
        /// 타입 변환 코드 생성
        /// </summary>
        private static string GenerateTypeConversionCode(string fieldName, string oldType, string newType)
        {
            string varName = fieldName.Replace(".", "_").Replace("?", "");
            if (varName.StartsWith("data_"))
                varName = varName.Substring(5);

            // 기본 타입 변환 규칙
            if (oldType == "number" && newType == "string")
            {
                return $"const converted_{varName} = String(data.{fieldName} ?? \"\");";
            }
            else if (oldType == "string" && newType == "number")
            {
                return $"const converted_{varName} = Number(data.{fieldName}) || 0;";
            }
            else if (oldType == "boolean" && newType == "string")
            {
                return $"const converted_{varName} = String(data.{fieldName} ?? false);";
            }
            else if (oldType == "string" && newType == "boolean")
            {
                return $"const converted_{varName} = data.{fieldName} === \"true\";";
            }
            else if (oldType == "number" && newType == "boolean")
            {
                return $"const converted_{varName} = Boolean(data.{fieldName});";
            }
            else if (oldType == "boolean" && newType == "number")
            {
                return $"const converted_{varName} = data.{fieldName} ? 1 : 0;";
            }
            else if (newType == "ModValueInt" && (oldType == "number" || oldType == "string"))
            {
                return $"const converted_{varName} = ModValueInt.create(Number(data.{fieldName}) || 0);";
            }
            else if (oldType == "ModValueInt" && newType == "number")
            {
                return $"const converted_{varName} = data.{fieldName}?.GetValue() ?? 0;";
            }
            else
            {
                // 알 수 없는 타입 변환은 TODO 표시
                return $"const converted_{varName} = data.{fieldName}; // TODO: {oldType} -> {newType} 변환 로직 필요";
            }
        }

        /// <summary>
        /// 전체 마이그레이션 파일 생성
        /// </summary>
        public static string GenerateFullMigrationFile(string coreDataName, SchemaHistory history)
        {
            var sb = new StringBuilder();

            // 사용된 타입 수집
            HashSet<string> usedTypes = CollectUsedTypes(history.Versions);

            // 헤더 (import 포함)
            sb.Append(GenerateFileHeader(coreDataName, usedTypes));

            // 인터페이스 체인
            sb.Append(GenerateInterfaceChain(coreDataName, history.Versions));
            sb.AppendLine();

            // 마이그레이션 함수
            sb.Append(GenerateMigrationObject(coreDataName, history.Versions));

            return sb.ToString();
        }

        /// <summary>
        /// CoreDataVersions.generated.ts 파일 생성
        /// </summary>
        public static string GenerateVersionsFile(Dictionary<string, string> coreDataVersions)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file was generated; DO NOT EDIT!");
            sb.AppendLine("// source: CodeGenerator_CoreDataMigration.cs");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("export const CoreDataLatestVersion: { [key: string]: string } = {");

            var sortedKeys = coreDataVersions.Keys.OrderBy(k => k).ToList();
            for (int i = 0; i < sortedKeys.Count; i++)
            {
                string key = sortedKeys[i];
                string version = coreDataVersions[key];
                string comma = i < sortedKeys.Count - 1 ? "," : "";
                sb.AppendLine($"{INDENT1}\"{key}\": \"{version}\"{comma}");
            }

            sb.AppendLine("};");

            return sb.ToString();
        }

        /// <summary>
        /// 메인 CoreDataMigration.ts에 추가할 import 문 생성
        /// </summary>
        public static string GenerateMainImports(List<string> coreDataNames)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine("// Auto-generated imports (DO NOT EDIT)");
            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine("import { CoreDataLatestVersion as GeneratedVersions } from \"./Generated/CoreDataVersions.generated\";");

            foreach (string name in coreDataNames.OrderBy(n => n))
            {
                sb.AppendLine($"import {{ {name}_Migrations_Generated }} from \"./Generated/{name}_migrations.generated\";");
            }

            return sb.ToString();
        }

        /// <summary>
        /// MigrationFunc 객체 병합 코드 생성
        /// </summary>
        public static string GenerateMergedMigrationFunc(List<string> coreDataNames)
        {
            var sb = new StringBuilder();

            sb.AppendLine();
            sb.AppendLine("// -----------------------------------------------");
            sb.AppendLine("// Merged Migration Functions (Auto + Manual)");
            sb.AppendLine("// -----------------------------------------------");

            foreach (string name in coreDataNames.OrderBy(n => n))
            {
                sb.AppendLine($"export const {name}_Migrations = {{");
                sb.AppendLine($"{INDENT1}...{name}_Migrations_Generated,");
                sb.AppendLine($"{INDENT1}// 수작업 추가 마이그레이션을 여기에 작성");
                sb.AppendLine("};");
                sb.AppendLine();
            }

            return sb.ToString();
        }
    }
}
